### ISSUE TITLE
ECE calculation

### ISSUE THREAD

**Issue by Razaimam45** [Bala93/CLIPCalib#2]
I ran your ECELoss() class from CLIPCalib/utils.py, but I'm having different ECE results for TPT than it is reported in this paper. It should be around 13.66 for Flowers as per your paper, but I'm getting 0.37 for some reason. Am I making some mistake somewhere?

Are you evaluating ECE at test-time for a single test-sample, or otherwise?

**Comment by Bala93** [comment]
Is this particular to Flowers or in general ?

**Comment by Razaimam45** [comment]
This is in generally across all datasets. 

To clarify: 
Since, in theory, ECE requires **m** samples, does that mean you save the confidence and prediction of each test sample, and when testing is done for _whole_ dataset, you calculate the ECE using the saved confidences and predictions of _all samples_?
 
Is it not like Top-1 and Top-5 accuracy, which are computed for each test sample _individually_??

**Comment by Bala93** [comment]
Yeah, I agree with "calculate the ECE using the saved confidences and predictions of all samples"
